// variable declarations
variable "name" {}
variable "node_vm_size" {}
variable "location" {}
variable "network_policy" {}
variable "network_plugin" {}
variable "address_space" {}
variable "os_disk_size_gb" {}
variable "namespace" {}
variable "coder_version" {}
variable "min_count" {}
variable "max_count" {}