// variable declarations
variable "region" {}
variable "project_id" {}
variable "name" {}
variable "disk_size_gb" {}
variable "image_type" {}
variable "machine_type" {}
variable "namespace" {}
variable "coder_version" {}
variable "min_node_count" {}
variable "max_node_count" {}
